### ISSUE TITLE
Statistic Chart missing after WP upgrade

### ISSUE THREAD

**Issue by alexmaiorino** [CastosHQ/Seriously-Simple-Stats#69]
After the last WP upgrade to version 5.4.2 statistics charts from Seriously Simple Stats went missing. They do not show either at the start panel in WP or in Statistics at the podcast session. Any fixes for it?
![image](https://user-images.githubusercontent.com/65421803/84597713-3fcea700-ae3c-11ea-83a5-c6b3e49c64b9.png)

**Comment by jonathanbossenger** [comment]
@alexmaiorino thanks for your patience here, this was fixed by #70 version 1.2.8 and is now available from the WP plugin repository.
