### ISSUE TITLE
Menu not displaying. 

### ISSUE THREAD

**Issue by bph** [CastosHQ/Seriously-Simple-Stats#92]
I seems to have lost my stats menu and I am just hoping I haven't lost the stats... 
I have both plugin installed. 

![Screen Shot 2022-07-10 at 10 39 20](https://user-images.githubusercontent.com/39980/178149584-32a3b1c1-4c28-4bfe-9795-71988c6b6925.png)

But there is no "Stats" menu

It doesn't even show in Site Health Troubleshooting Mode and only those two plugins installed. 
![Screen Shot 2022-07-10 at 10 42 24](https://user-images.githubusercontent.com/39980/178149654-0a8095ff-f0be-48e2-b44a-1e8ddc0d8322.png)

I host on Pantheon

**Comment by jonathanbossenger** [comment]
@bph it's possible this could be a plugin conflict, I've checked my site, running SSP 2.14.2 and stats 1.3.0 and the Stats menu does appear.
![WordPress-Updates-‹-Jonathan-Bossenger-—-WordPress](https://user-images.githubusercontent.com/180629/178150746-b9cbaf4b-b542-4ef2-a836-9e4aec0c30ac.png)

**Comment by bph** [comment]
Well - my site is in troubleshooting mode ( all plugins disabled except the two)

**Comment by jonathanbossenger** [comment]
> Well - my site is in troubleshooting mode ( all plugins disabled except the two)

Ah, that is indeed interesting and frustrating.

https://jonathanbossenger.com/wp-admin/edit.php?post_type=podcast&page=podcast_stats

**Comment by bph** [comment]
Seems to be a permission problem... "Sorry, you are not allowed to access this page." - at least that explains the menu not displayed...

**Comment by jonathanbossenger** [comment]
Hmmm, out of interest, what PHP version are you running?

**Comment by bph** [comment]
PHP 7.4.30 (Supports 64bit values) - would that make any difference?

**Comment by jonathanbossenger** [comment]
Probably not, I thought maybe this was a PHP 8 issue.

**Comment by zahardev** [comment]
@bph Could you please check the folder names, especially the folder of the seriously-simple-podcasting plugin? It looks like the Stats plugin checks for seriously-simple-podcasting folder, and if it's renamed, it might not work. Also, when has it stopped working?

**Comment by bph** [comment]
Sorry for the delay. Thanks for the suggestion. 
Both directories have the same owners so there shouldn't be a problem with permissions. 
I provide you with the screenshot of the folders list, maybe you see something that stands out. 

Here is the screenshot of the stats directory

<img width="937" alt="Screen Shot 2022-09-03 at 6 37 06 PM" src="https://user-images.githubusercontent.com/39980/188289663-73c886c5-b879-4dd9-be98-134037954637.png">

And this is the Seriously-Simple-Podcasting directory

<img width="961" alt="Screen Shot 2022-09-03 at 6 39 47 PM" src="https://user-images.githubusercontent.com/39980/188289672-5fcbed9f-1d75-44e3-b383-deca17c75b69.png">

**Comment by bph** [comment]
@zahardev Sergey, could you please take a look at it again? It's really hard to do all the work on the podcast, without seeing if there are even listeners on the episode. :-)

**Comment by bph** [comment]
@zahardev After the latest updates of both the plugin and the stats add-on the menu shows again. So thank you for that. But it also didn't track anything since June. Found months not stats.
