### ISSUE TITLE
Public API for stats?

### ISSUE THREAD

**Issue by ethancedwards8** [CastosHQ/Seriously-Simple-Stats#93]
Hello all,

I'm considering developing an iOS app that will pull the stats from SSP-Stats instances and display them in a widget on your home screen. That being said, is there an API route that is publicly available for the plugin? Is there any documentation on it? I'm willing to piece everything together, but I'm not sure if one exists and I thought I would at least ask first.

Thanks.

**Comment by jonathanbossenger** [comment]
Hi @ethancedwards8.

I'm no longer employed by Castos, so I'm not the right person to ask about that. However you are correct, there are no public API endpoints for the stats. 

My suggestion would be to go with option 2) and create your own custom plugin that uses [register_rest_route](https://developer.wordpress.org/reference/functions/register_rest_route/) to create a custom API endpoint with a route to fetch the data you need for your mobile app. 

If you need help with building this, I recently completed a couple of Learn WordPress tutorials on how to use/interact with and extend the [WP REST API](https://learn.wordpress.org/?s=wp+rest+api), and this tutorial on [Custom Routes and Endpoints](https://learn.wordpress.org/tutorial/wordpress-rest-api-custom-routes-endpoints/) might be useful.

I also recommend the [Custom endpoints](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/) section of the WP REST API docs, as well as the section on [Controller Classes](https://developer.wordpress.org/rest-api/extending-the-rest-api/controller-classes/). Controller Classes will come in handy if you need to build a more robust custom set of routes and endpoints.

**Comment by ethancedwards8** [comment]
Hi @jonathanbossenger 

Thanks for the confirmation. 

Okay, that sounds like a good idea. Thanks for pointing me in the right direction. 

Great, those tutorials look like just what I need.

Thanks. I'm not super experienced with Wordpress so I'm sure those will come in handy.
